HW_8
nazarkiboba/Home-Works-for-R_D pull request #7
Opened 2023-12-16 10:47 UTC by nazarkiboba

2023-12-16 20:42 UTC, helen-black requested changes

2023-12-16 20:42 UTC, helen-black commented on HW real/HW_8/HW_8.cpp
> +void Secound_a(int num)
в завданні є декларація функції. твоя функція повинна виглядати так:
```c++
int factorial(int count)
```

2023-12-16 20:42 UTC, helen-black commented on HW real/HW_8/HW_8.cpp
> +  std::cout << factorial<<"\n\n";
функція повинна повертати результат, а не друкувати його
```c++
return factorial;
```

2023-12-16 20:42 UTC, helen-black commented on HW real/HW_8/HW_8.cpp
> +}*/
в тебе не виходить, бо факторіал повинен повертати результат, як я описала в попередніх коментарях. так легше зробити це завдання. Спробуй, будь ласка

2023-12-16 20:42 UTC, helen-black commented on HW real/HW_8/HW_8.cpp
> +}
не правильний вивід. якщо num == 5, має надрукувати
1 2 3 4 5.
що в тебе друкує?

2023-12-16 20:42 UTC, helen-black commented on HW real/HW_8/HW_8.cpp
> +	while ( i <= num)
можна видалити змінну i
```c++
while ( num > 0)
```

2023-12-16 20:42 UTC, helen-black commented on HW real/HW_8_1/HW_8.cpp
навіщо пушити однакові файли?)

2023-12-17 08:51 UTC, nazarkiboba commented on HW real/HW_8_1/HW_8.cpp
Це було випадково,я не навмисно.

2023-12-17 09:29 UTC, nazarkiboba commented
Я що зміг то й виправив,з факторіалами там біда:на фото показано як програма робе(воно буде в слаку тому що тут я не відправлю).А ось код який я переробив.

#include <iostream>

int factorial(int count);
int Secound_b(int num);
void Third_a(int num);
void Third_b(int num);
void Third_c(int num);
void Third_d(int num);

int main()
{

	std::cout << "Secound Work!\n" << "1)\n";
	{
		int last_num = 0;
		std::cout << "Enter the number to know factorial of this number: ";
		std::cin >> last_num;
		int factorial(last_num);
	}
	std::cout << "2)\n";
	{
		int last_num = 0;
		std::cout << "Enter the number to know factorial of this number: ";
		std::cin >> last_num;
		Secound_b(last_num);
	}
	std::cout << "Third Work!\n" << "a)\n";
	{
		int k = 0;
		std::cout << "Enter the number: ";
		std::cin >> k;
		Third_a(k);

		std::cout << "\nb)\n";
		int x = 0;
		std::cout << "Enter the number: ";
		std::cin >> x;
		Third_b(x);

		std::cout << "\nc)\n";
		int e = 0;
		std::cout << "Enter the number: ";
		std::cin >> e;
		Third_c(e);

		std::cout << "\nd)\n";
		int q = 0;
		std::cout << "Enter the number: ";
		std::cin >> q;
		Third_d(q);
	}
}

int factorial(int count)
{
	int int_factorial = 1;
	for (int i = 2; i <= count; i++)
	{
		int_factorial *= i;
		return int_factorial;
	}
	
	std::cout << int_factorial << "\n\n";
    
}
int Secound_b(int num)
{
	int factorial = --num;
	int sum = factorial * num;
	int i = num;
	if (i >= 2)
	{
		--i;
		Secound_b(sum * (num));
		return factorial;
	}
	
	std::cout << sum << "\n";
}
void Third_a(int num)
{
	
	while (num > 0)
	{
		std::cout << num << "\n";
		num--;
	}

}
void Third_b(int num)
{
	int number = 0;
	for (int i = 1; i <= num; i++)
	{
		number = +i;
		std::cout << number << "\n";
	}
}
void Third_c(int num)
{
	if (num < 1)
	{
		return;
	}
	std::cout << num << "\n";
	Third_c(num - 1);
}
void Third_d(int num)
{
	if (num < 1)
	{
		return;
	}
	Third_d(num - 1);
	std::cout << num << "\n";
}

2023-12-19 15:02 UTC, merged